# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-chat-hpa  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-chat
  minReplicas: 2
  maxReplicas: 6
  metrics:    
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
    # - type: External
    #   external:
    #     metric:
    #       name: active_connections
    #       selector:
    #         matchLabels:
              