apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-chat
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: go-chat
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: go-chat
    active: "true"
  type: LoadBalancer
  loadBalancerIP: 10.0.25.20
status:
  loadBalancer: {}